server:
  port: 8580
  servlet:
    context-path: /prueba-novatec/api/v1.0.0

spring:
    datasource:
        platform: h2
        driverClassName: org.h2.Driver
        jdbc-url: jdbc:h2:mem:testdb
        username: sa
        password: sa
        generate-unique-name: false
        hikari:
          maximum-pool-size: 8
          connection-timeout: 6000
          minimum-idle: 5
          idle-timeout: 15000
    h2:
        console:
            enabled: true
            path: /h2-console
