CREATE TABLE PUBLIC.especialidad (
	id INTEGER NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	descripcion VARCHAR(100) NOT NULL,
	CONSTRAINT ESPECIALIDAD_PK PRIMARY KEY (id)
);
COMMENT ON TABLE PUBLIC.especialidad IS 'Tabla para las especialidades del profesor';


CREATE TABLE PUBLIC.profesor (
	id INTEGER NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	apellido VARCHAR(100) NOT NULL,
	id_especialidad INTEGER NOT NULL,
	CONSTRAINT PROFESOR_PK PRIMARY KEY (id)
);

COMMENT ON TABLE PUBLIC.profesor IS 'Tabla para profesores';

ALTER TABLE PUBLIC.profesor ADD CONSTRAINT PROFESOR_FK FOREIGN KEY (id_especialidad) REFERENCES PUBLIC.especialidad(id);


CREATE TABLE PUBLIC.alumno (
	id INTEGER NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	apellido VARCHAR(100) NOT NULL,
	curso VARCHAR(100) NOT NULL,
	CONSTRAINT ALUMNO_PK PRIMARY KEY (id)
);
COMMENT ON TABLE PUBLIC.alumno IS 'tabla de alumnos';



